baseURL = 'https://y2kwallpaper.com'
languageCode = 'en-us'
title = 'Y2K Wallpaper Art'
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
[params]
  [params.socialIcons]
    instagram = "https://www.instagram.com/ideate.xyz"
    website = "https://ideate.xyz"